logging.level.org.apache.tomcat=DEBUG
logging.level.org.apache.catalina=DEBUG

# ======= Feature toggle =======
# Mettre a true quand Docker (RabbitMQ + MailHog) tourne
app.rabbitmq.enabled=true

# ======= RabbitMQ =======
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ======= Mail (MailHog via Docker sur port 1025) =======
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false