events {}

http {

    resolver 127.0.0.11 ipv6=off;

    # ---- Upstreams ----
    upstream auth-service {
        server host.docker.internal:8080;
    }

    upstream service-a {
        server host.docker.internal:8080;
    }

    upstream service-b {
        server host.docker.internal:8080;
    }

    server {
        listen 80;

        # ---- Subrequest d'authentification ----
        location = /_auth {
            internal;
            proxy_pass              http://auth-service/auth/validate;
            proxy_pass_request_body off;
            proxy_set_header        Content-Length "";
            #proxy_set_header        Host $proxy_host;
            proxy_set_header        Host "localhost"; 
            proxy_set_header        Authorization $http_authorization;
            proxy_set_header        X-Target-Service $target_service;
        }

        # ---- 403 uniforme ----
        location = /_forbidden {
            internal;
            return 403 '{"error":"Forbidden"}';
            default_type application/json;
        }

        # ---- Routes publiques auth (login, register, logout...) ----
        location /auth/ {
            proxy_pass       http://auth-service;
            #proxy_set_header        Host $proxy_host;
            proxy_set_header        Host "localhost"; 
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---- Service A ----
        location /a/ {
            if ($http_authorization = "") { return 403; }
            set $target_service "A";
            auth_request /_auth;
            error_page 401 =403 /_forbidden;
            error_page 403 =403 /_forbidden;
            proxy_pass       http://service-a;
            #proxy_set_header        Host $proxy_host;
            proxy_set_header Host "localhost"; 
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---- Service B ----
        location /b/ {
            if ($http_authorization = "") { return 403; }
            set $target_service "B";
            auth_request /_auth;
            error_page 401 =403 /_forbidden;
            error_page 403 =403 /_forbidden;
            proxy_pass       http://service-b;
            #proxy_set_header        Host $proxy_host;
            proxy_set_header         Host "localhost"; 
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}